from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14c6275d697e'
down_revision: Union[str, Sequence[str], None] = '2f58ed84049f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # --- РУЧНОЕ СОЗДАНИЕ ENUM ТИПОВ ДЛЯ POSTGRESQL (ИСПРАВЛЕНИЕ ОШИБКИ) ---
    # ENUM для AbilityEnum (используется для primary_ability, st_enum_1, st_enum_2)
    ABILITY_TYPES = "'Strength', 'Dexterity', 'Constitution', 'Intelligence', 'Wisdom', 'Charisma'"
    op.execute(f"CREATE TYPE primary_ability_enum AS ENUM ({ABILITY_TYPES});")
    op.execute(f"CREATE TYPE st_enum_1 AS ENUM ({ABILITY_TYPES});")
    op.execute(f"CREATE TYPE st_enum_2 AS ENUM ({ABILITY_TYPES});")
    
    # ENUM для ArmorTypeEnum
    ARMOR_TYPES = "'LIGHT', 'MEDIUM', 'HEAVY', 'SHIELD', 'NONE'"
    op.execute(f"CREATE TYPE armor_type_enum AS ENUM ({ARMOR_TYPES});")
    
    # ENUM для DiceTypeEnum (hit_dice, damage_dice_enum)
    DICE_TYPES = "'D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100'"
    op.execute(f"CREATE TYPE hit_dice_enum AS ENUM ({DICE_TYPES});")

    # ### commands auto generated by Alembic - original section ###
    # В Alembic'е 'classes' видимо называется 'dnd_classes', но я использую имя из вашей миграции
    op.add_column('classes', sa.Column('primary_ability', postgresql.ENUM('Strength', 'Dexterity', 'Constitution', 'Intelligence', 'Wisdom', 'Charisma', name='primary_ability_enum'), nullable=False))
    op.add_column('classes', sa.Column('starting_gold', sa.Integer(), nullable=True))
    op.add_column('classes', sa.Column('armor_proficiency', postgresql.ENUM('LIGHT', 'MEDIUM', 'HEAVY', 'SHIELD', 'NONE', name='armor_type_enum'), nullable=False))
    
    # Заменяем типы на уже созданные ENUMs
    op.alter_column('classes', 'hit_dice',
               existing_type=postgresql.ENUM('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice'),
               type_=postgresql.ENUM('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice_enum'),
               existing_nullable=False,
               postgresql_using='hit_dice::text::hit_dice_enum') # Добавляем приведение типов для безопасности
               
    op.alter_column('classes', 'saving_throw_1',
               existing_type=postgresql.ENUM('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='saving_throw_1'),
               type_=postgresql.ENUM('Strength', 'Dexterity', 'Constitution', 'Intelligence', 'Wisdom', 'Charisma', name='st_enum_1'),
               existing_nullable=False,
               postgresql_using='saving_throw_1::text::st_enum_1')
               
    op.alter_column('classes', 'saving_throw_2',
               existing_type=postgresql.ENUM('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='saving_throw_2'),
               type_=postgresql.ENUM('Strength', 'Dexterity', 'Constitution', 'Intelligence', 'Wisdom', 'Charisma', name='st_enum_2'),
               existing_nullable=False,
               postgresql_using='saving_throw_2::text::st_enum_2')

    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_source'), table_name='classes')
    op.drop_column('classes', 'source')
    op.drop_column('classes', 'max_armor_mastery')
    op.drop_column('classes', 'main_ability')
    op.drop_column('classes', 'description')
    op.drop_column('classes', 'proficient_with_shields')
    op.drop_column('classes', 'starting_skills_count')
    op.drop_column('classes', 'weapon_proficiencies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - original section ###
    op.add_column('classes', sa.Column('weapon_proficiencies', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('starting_skills_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('proficient_with_shields', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('main_ability', postgresql.ENUM('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='ability'), autoincrement=False, nullable=True))
    op.add_column('classes', sa.Column('max_armor_mastery', postgresql.ENUM('NONE', 'LIGHT', 'MEDIUM', 'HEAVY', name='max_armor_mastery'), autoincrement=False, nullable=False))
    op.add_column('classes', sa.Column('source', postgresql.ENUM('PH14', 'XGE', 'MMOT', 'CUSTOM', name='source'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_classes_source'), 'classes', ['source'], unique=False)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.alter_column('classes', 'saving_throw_2',
               existing_type=sa.Enum('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='st_enum_2'),
               type_=postgresql.ENUM('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='saving_throw_2'),
               existing_nullable=False)
    op.alter_column('classes', 'saving_throw_1',
               existing_type=sa.Enum('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='st_enum_1'),
               type_=postgresql.ENUM('STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA', name='saving_throw_1'),
               existing_nullable=False)
    op.alter_column('classes', 'hit_dice',
               existing_type=sa.Enum('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice_enum'),
               type_=postgresql.ENUM('D4', 'D6', 'D8', 'D10', 'D12', 'D20', 'D100', name='hit_dice'),
               existing_nullable=False)
    op.drop_column('classes', 'armor_proficiency')
    op.drop_column('classes', 'starting_gold')
    op.drop_column('classes', 'primary_ability')
    # ### end Alembic commands ###

    # --- РУЧНОЕ УДАЛЕНИЕ ENUM ТИПОВ ДЛЯ POSTGRESQL ---
    op.execute("DROP TYPE primary_ability_enum;")
    op.execute("DROP TYPE st_enum_1;")
    op.execute("DROP TYPE st_enum_2;")
    op.execute("DROP TYPE armor_type_enum;")
    op.execute("DROP TYPE hit_dice_enum;")
    # (damage_dice_enum не создается в этой миграции, поэтому не удаляем)