"""initial

Revision ID: 2f58ed84049f
Revises:
Create Date: 2025-12-01 02:26:40.408628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f58ed84049f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characteristics_sheets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("str_score", sa.Integer(), nullable=False),
        sa.Column("dex_score", sa.Integer(), nullable=False),
        sa.Column("con_score", sa.Integer(), nullable=False),
        sa.Column("int_score", sa.Integer(), nullable=False),
        sa.Column("wis_score", sa.Integer(), nullable=False),
        sa.Column("cha_score", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_characteristics_sheets_id"),
        "characteristics_sheets",
        ["id"],
        unique=False,
    )
    op.create_table(
        "classes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "source",
            sa.Enum("PH14", "XGE", "MMOT", "CUSTOM", name="source"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "hit_dice",
            sa.Enum("D4", "D6", "D8", "D10", "D12", "D20", "D100", name="hit_dice"),
            nullable=False,
        ),
        sa.Column(
            "main_ability",
            sa.Enum("STR", "DEX", "CON", "INT", "WIS", "CHA", name="ability"),
            nullable=True,
        ),
        sa.Column(
            "max_armor_mastery",
            sa.Enum("NONE", "LIGHT", "MEDIUM", "HEAVY", name="max_armor_mastery"),
            nullable=False,
        ),
        sa.Column("proficient_with_shields", sa.Boolean(), nullable=True),
        sa.Column(
            "saving_throw_1",
            sa.Enum("STR", "DEX", "CON", "INT", "WIS", "CHA", name="saving_throw_1"),
            nullable=False,
        ),
        sa.Column(
            "saving_throw_2",
            sa.Enum("STR", "DEX", "CON", "INT", "WIS", "CHA", name="saving_throw_2"),
            nullable=False,
        ),
        sa.Column("starting_skills_count", sa.Integer(), nullable=True),
        sa.Column("weapon_proficiencies", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classes_id"), "classes", ["id"], unique=False)
    op.create_index(op.f("ix_classes_source"), "classes", ["source"], unique=False)
    op.create_table(
        "races",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "source",
            sa.Enum("PH14", "XGE", "MMOT", "CUSTOM", name="source"),
            nullable=False,
        ),
        sa.Column("abilities", sa.Text(), nullable=True),
        sa.Column("appearance", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("languages", sa.String(length=255), nullable=True),
        sa.Column("max_lifespan", sa.Integer(), nullable=True),
        sa.Column(
            "size", sa.Enum("SMALL", "MEDIUM", "LARGE", name="size"), nullable=False
        ),
        sa.Column("speed_ft", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_races_id"), "races", ["id"], unique=False)
    op.create_index(op.f("ix_races_source"), "races", ["source"], unique=False)
    op.create_table(
        "weapons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "source",
            sa.Enum("PH14", "XGE", "MMOT", "CUSTOM", name="source"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum("SIMPLE", "MARTIAL", name="weapon_category"),
            nullable=False,
        ),
        sa.Column("damage_dice", sa.String(length=10), nullable=False),
        sa.Column(
            "damage_dice_type",
            sa.Enum("D4", "D6", "D8", "D10", "D12", "D20", "D100", name="damage_dice"),
            nullable=False,
        ),
        sa.Column(
            "damage_type",
            sa.Enum("SLASHING", "PIERCING", "BLUDGEONING", name="damage_type"),
            nullable=False,
        ),
        sa.Column("properties", sa.Text(), nullable=True),
        sa.Column("range_long", sa.Integer(), nullable=True),
        sa.Column("range_normal", sa.Integer(), nullable=True),
        sa.Column(
            "weapon_type",
            sa.Enum("MELEE", "RANGED", name="weapon_type"),
            nullable=False,
        ),
        sa.Column("weight_lb", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weapons_id"), "weapons", ["id"], unique=False)
    op.create_index(op.f("ix_weapons_name"), "weapons", ["name"], unique=False)
    op.create_index(op.f("ix_weapons_source"), "weapons", ["source"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("current_hp", sa.Integer(), nullable=True),
        sa.Column("max_hp", sa.Integer(), nullable=True),
        sa.Column("race_id", sa.Integer(), nullable=False),
        sa.Column("race_id_secondary", sa.Integer(), nullable=True),
        sa.Column("class_id", sa.Integer(), nullable=False),
        sa.Column("class_id_secondary", sa.Integer(), nullable=True),
        sa.Column("sheet_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["class_id_secondary"],
            ["classes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["race_id_secondary"],
            ["races.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sheet_id"],
            ["characteristics_sheets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sheet_id"),
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.create_table(
        "character_weapon_association",
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("weapon_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["weapon_id"],
            ["weapons.id"],
        ),
        sa.PrimaryKeyConstraint("character_id", "weapon_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("character_weapon_association")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_weapons_source"), table_name="weapons")
    op.drop_index(op.f("ix_weapons_name"), table_name="weapons")
    op.drop_index(op.f("ix_weapons_id"), table_name="weapons")
    op.drop_table("weapons")
    op.drop_index(op.f("ix_races_source"), table_name="races")
    op.drop_index(op.f("ix_races_id"), table_name="races")
    op.drop_table("races")
    op.drop_index(op.f("ix_classes_source"), table_name="classes")
    op.drop_index(op.f("ix_classes_id"), table_name="classes")
    op.drop_table("classes")
    op.drop_index(
        op.f("ix_characteristics_sheets_id"), table_name="characteristics_sheets"
    )
    op.drop_table("characteristics_sheets")
    # ### end Alembic commands ###
